name: Checkout Tests

# one dispatch
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Install Playwright dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright pytest-html

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Checkout Tests
        run: |
          REPORT_NAME=checkout-report-${{ github.run_id }}.html
          echo "REPORT_NAME=$REPORT_NAME" >> $GITHUB_ENV
          pytest -m checkout tests --maxfail=1 --disable-warnings --html=reports/$REPORT_NAME --self-contained-html

      - name: Upload Checkout Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkout-test-report
          path: reports/${{ env.REPORT_NAME }}

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone gh-pages branch
        run: |
          git clone --branch gh-pages https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/yasiqb89/gh-pages.git gh-pages

      - name: Copy report to gh-pages
        run: |
          cp reports/${{ env.REPORT_NAME }} gh-pages/${{ env.REPORT_NAME }}
          cp reports/${{ env.REPORT_NAME }} gh-pages/index.html

      - name: Push report to gh-pages
        run: |
          cd gh-pages
          git add ${{ env.REPORT_NAME }} index.html
          git commit -m "Add Checkout report ${{ env.REPORT_NAME }}"
          git push origin gh-pages

      - name: Send Slack notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "✅ *Checkout Tests Completed*\n📄 <https://yasiqb89.github.io/gh-pages/${{ env.REPORT_NAME }}|View HTML Report>\n🔗 <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub Run Log>"
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
