name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to latest version
        with:
          python-version: "3.10.13"  # Consider upgrading to 3.11 or 3.12

      - name: Install Playwright dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright pytest-html

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Playwright Tests
        run: pytest tests --maxfail=1 --disable-warnings --html=reports/playwright-report.html --self-contained-html
        # Added --headless for CI compatibility

      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: reports/playwright-report.html  # Fixed to match the generated report path