name: Smoke Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      # SETUP & RUN TESTS
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Install Playwright dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright pytest-html

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Smoke Tests
        run: |
          REPORT_NAME=smoke-report-${{ github.run_id }}.html
          echo "REPORT_NAME=$REPORT_NAME" >> $GITHUB_ENV
          pytest -m smoke tests --maxfail=1 --disable-warnings \
                --html=reports/$REPORT_NAME --self-contained-html

      - name: Upload Smoke Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-report
          path: reports/${{ env.REPORT_NAME }}

      # PUBLISH TO GH-PAGES
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"

      - name: Clone gh-pages branch
        run: |
          git clone --branch gh-pages \
            https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/yasiqb89/gh-pages.git gh-pages

      - name: Copy report to gh-pages
        run: |
          cp reports/${{ env.REPORT_NAME }} gh-pages/${{ env.REPORT_NAME }}
          cp reports/${{ env.REPORT_NAME }} gh-pages/index.html

      - name: Push report to gh-pages
        run: |
          cd gh-pages
          git add .
          git commit -m "Add smoke report ${{ env.REPORT_NAME }}"
          git push origin gh-pages

      # NOTIFY N8N
      - name: Notify n8n that report is ready
        if: always()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d "{
                  \"suite\"      : \"smoke\",
                  \"run_id\"     : \"${GITHUB_RUN_ID}\",
                  \"report_url\" : \"https://yasiqb89.github.io/gh-pages/${REPORT_NAME}\"
                }" \
            ${{ secrets.N8N_WEBHOOK_URL }}

      # SLACK SUMMARY
      - name: Send Slack notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "✅ *Smoke Tests Completed*\n📄 <https://yasiqb89.github.io/gh-pages/${{ env.REPORT_NAME }}|View HTML Report>\n🔗 <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub Run Log>"
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
