# .github/workflows/smoke-tests.yml
name: Smoke Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      # SET-UP
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright pytest-html

      - name: Install Playwright browsers
        run: playwright install --with-deps

      # RUN TESTS & PRODUCE REPORTS
      - name: Run smoke tests
        run: |
          REPORT_NAME="smoke-report-${{ github.run_id }}.html"
          echo "REPORT_NAME=$REPORT_NAME" >> "$GITHUB_ENV"

          pytest -m smoke tests --maxfail=1 --disable-warnings \
                --html="reports/$REPORT_NAME" --self-contained-html \
                --junitxml="results.xml"

      # UPLOAD HTML ARTIFACT
      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-html
          path: reports/${{ env.REPORT_NAME }}

      # PUSH REPORT TO gh-pages
      - name: Push report to gh-pages
        if: always()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"

          git clone --branch gh-pages \
            https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/yasiqb89/gh-pages.git gh-pages

          cp "reports/${REPORT_NAME}" "gh-pages/${REPORT_NAME}"
          cp "reports/${REPORT_NAME}" "gh-pages/index.html"

          cd gh-pages
          git add .
          git commit -m "Add smoke report ${REPORT_NAME}"
          git push origin gh-pages

      # NOTIFY n8n
      - name: Notify n8n
        if: always()
        run: |
          cat > payload.json <<EOF
          {
            "suite"      : "smoke",
            "run_id"     : "${GITHUB_RUN_ID}",
            "report_url" : "https://yasiqb89.github.io/gh-pages/${REPORT_NAME}",
            "run_url"    : "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "status"     : "${{ job.status }}"
          }
          EOF

          curl -s -X POST -H 'Content-Type: application/json' \
               --data @payload.json \
               ${{ secrets.N8N_WEBHOOK_URL }}

      # SLACK SUMMARY
      - name: Slack summary
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "🧪 *Smoke Tests* - *${{ job.status }}* \n📄 <https://yasiqb89.github.io/gh-pages/${{ env.REPORT_NAME }}|HTML Report> \n🔗 <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub Run Log>"
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
