name: Smoke Tests

#one dispatch
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Install Playwright dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright pytest-html

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Smoke Tests
        run: pytest -m smoke tests --maxfail=1 --disable-warnings --html=reports/login-report.html --self-contained-html

      - name: Upload Smoke Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: login-smoke-report
          path: reports/smoke-report.html

      - name: Send Slack notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "✅ *Smoke Tests Completed*.\n🔗 <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Report>"
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
